#include "netlink/handlers.h"
#include <arpa/inet.h>
#include <batman.h>
#include <ifaddrs.h>
#include <linux/batman_adv.h>
#include <netinet/in.h>
#include <netlink/genl/ctrl.h>
#include <netlink/genl/genl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <view.h>

static gboolean resolve_ip_from_arp(const char *mac_addr, char *ip_out,
                                    size_t ip_buf_len) {
  FILE *arp_file = fopen("/proc/net/arp", "r");
  if (!arp_file) {
    return FALSE;
  }

  char line[256];
  gboolean found = FALSE;

  // Skip the header line ("IP address       HW type     Flags...")
  if (!fgets(line, sizeof(line), arp_file)) {
    fclose(arp_file);
    return FALSE;
  }

  while (fgets(line, sizeof(line), arp_file)) {
    char ip[64], hw_type[16], flags[16], hw_addr[18], mask[16], dev[32];

    // Parse the standard Linux ARP table format
    if (sscanf(line, "%63s %15s %15s %17s %15s %31s", ip, hw_type, flags,
               hw_addr, mask, dev) != 6) {
      continue;
    }

    // Case-insensitive comparison of the MAC address
    if (g_ascii_strcasecmp(hw_addr, mac_addr) == 0) {
      g_strlcpy(ip_out, ip, ip_buf_len);
      found = TRUE;
      break;
    }
  }

  fclose(arp_file);
  return found;
}

int fetch_mesh_neighbors(MeshNeighbor neighbors_out[]) {
    FILE *fp;
    char line[256];
    int count = 0;

    /* * Execute 'batctl originator' via a system pipe read.
     * This commands the OS to dump the current live routing table.
     */
    fp = popen("batctl originator", "r");
    if (fp == NULL) {
        perror("Failed to execute batctl command");
        return 0;
    }

    // Skip the header text rows generated by batctl
    // First line: "Originator      last-seen (# TQ) Nexthop [wlan0]:"
    // Second line: Header separators or empty spacing.

    int line_index = 0;
    while (fgets(line, sizeof(line), fp) != NULL) {
        line_index++;
        if (line_index <= 2) {
            continue; // Skip headers safely
        }

        char orig_mac[18];
        char nexthop_mac[18];
        int tq = 0;
        float last_seen = 0.0;
        char iface[32];

        /* * Parse standard batctl format:
         * e.g., "b8:27:eb:11:22:33   0.420s   (240) b8:27:eb:11:22:33 [wlan0]"
         */
        if (sscanf(line, "%17s %fs (%d) %17s [%31[^]]]", 
                   orig_mac, &last_seen, &tq, nexthop_mac, iface) >= 4) {
            
            // Avoid buffer overflow bounds check
            if (count >= MESH_MAX_NEIGHBORS) break;

            // 1. Copy over the discovered node's unique hardware signature
            g_strlcpy(neighbors_out[count].mac, orig_mac, sizeof(neighbors_out[count].mac));
            
            // 2. Map the extracted kernel Transmission Quality link factor metric
            neighbors_out[count].link_quality = tq;

            // 3. Resolve the Layer-3 IP from your ARP database cache mapping
            if (!resolve_ip_from_arp(orig_mac, neighbors_out[count].ip, sizeof(neighbors_out[count].ip))) {
                // If it isn't found in ARP yet, copy a safe fallback label string
                g_strlcpy(neighbors_out[count].ip, "Resolving...", sizeof(neighbors_out[count].ip));
            }

            count++;
        }
    }

    pclose(fp);
    return count; // Returns the clean number of found alive nodes back to main.c
}

int on_new_bat_node(struct nl_msg *msg, void *arg) {
  GtkData* gtk_data = (GtkData *) arg;
  MeshNeighbor *neighbor;
  struct nlmsghdr *nlh = nlmsg_hdr(msg);

  struct nlattr *attrs[BATADV_ATTR_MAX + 1];

  if (genlmsg_parse(nlh, 0, attrs, BATADV_ATTR_MAX, NULL) < 0) {
    g_printerr("[Netlink] Error: Failed to parse kernel message attributes.\n");
    return NL_SKIP;
  }

  if (attrs[BATADV_ATTR_ORIG_ADDRESS]) {
    uint8_t *mac_bytes = (uint8_t *)nla_data(attrs[BATADV_ATTR_ORIG_ADDRESS]);

    snprintf(neighbor->mac, sizeof(neighbor->mac),
             "%02x:%02x:%02x:%02x:%02x:%02x", mac_bytes[0], mac_bytes[1],
             mac_bytes[2], mac_bytes[3], mac_bytes[4], mac_bytes[5]);

  } else {
    return NL_SKIP;
  }

  if (attrs[BATADV_ATTR_TQ]) {
    neighbor->link_quality = nla_get_u8(attrs[BATADV_ATTR_TQ]);
    g_print("                Link Metric Quality (TQ): %d/255\n",
            neighbor->link_quality);
  } else {
    neighbor->link_quality = 0; // Default fallback if unavailable
  }

  if (!resolve_ip_from_arp(neighbor->mac, neighbor->ip, sizeof(neighbor->ip))) {
    g_strlcpy(neighbor->ip, "IP_UNRESOLVED", sizeof(neighbor->ip));
    return NL_SKIP;
  }

  add_button(gtk_data, neighbor->ip);

  return NL_OK;
}

int get_local_ip(const char *interface, char *ip) {
  struct ifaddrs *ifap, *ifa;
  struct sockaddr_in *sa;

  getifaddrs(&ifap);
  for (ifa = ifap; ifa; ifa = ifa->ifa_next) {
    if (ifa->ifa_addr && ifa->ifa_addr->sa_family == AF_INET) {
      if (strcmp(interface, ifa->ifa_name) == 0) {
        sa = (struct sockaddr_in *)ifa->ifa_addr;
        ip = inet_ntoa(sa->sin_addr);
        freeifaddrs(ifap);
        return 1;
      }
    }
  }
  freeifaddrs(ifap);
  return 0;
}
